site_name: Aphrilâ€™s Widget Library
site_description: Modular Common UI based widgets for Unreal Engine
site_author: Silverkeep Studios
site_url: https://breedurbin.github.io/Aphrils-Widget-Library/

repo_name: BreeDurbin/Aphrils-Widget-Library
repo_url: https://github.com/BreeDurbin/Aphrils-Widget-Library
    
theme:
  name: material
  logo:    assets/Awl_Logo.png
  favicon: assets/Awl_favicon.png
  features:
    - navigation.sections
    - navigation.expand
    - navigation.top
    - content.code.copy
  palette:
    primary:
      main: "e8d8b8"        # top bar / primary color
      contrast: "8a9a5b"    # text color for top bar


markdown_extensions:
  - admonition
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.details
  - pymdownx.inlinehilite
  - attr_list

nav:
  - Overview:                         index.md
  - Requirements:                     requirements.md
  - Button-Pack:
      - Installation:                 button-pack/button-pack-installation.md
      - Widget Blueprint Parameters:  button-pack/widget-blueprint-parameters.md
      - Material Parameters:          button-pack/material-parameters.md
      - Changelog:                    button-pack/changelog.md
  - General Guides: 
      - Workflow:                     general-guides/workflow.md
      - Creating New Themes:          general-guides/creating-new-themes.md
      - Channel Packing:              general-guides/channel-packing.md
  - Misc: 
      - Design Pillars:               misc/design-pillars.md
      - About:                        misc/about.md

extra: 
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/BreeDurbin