site_name: Aphrilâ€™s Widget Library
site_description: Modular Common UI based widgets for Unreal Engine
site_author: Silverkeep Studios
site_url: https://breedurbin.github.io/Aphrils-Widget-Library/

repo_name: BreeDurbin/Aphrils-Widget-Library
repo_url: https://github.com/BreeDurbin/Aphrils-Widget-Library

theme:
  name: material
  features:
    - navigation.sections
    - navigation.expand
    - navigation.top
    - content.code.copy
  palette:
    scheme: slate

markdown_extensions:
  - admonition
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.details
  - pymdownx.inlinehilite
  - attr_list

nav:
  - Overview:
      - Overview:              index.md
      - Requirements:          requirements.md
  - Button-Pack:
      - Installation:          button-pack/button-pack-installation.md
      - Styling:               button-pack/button-pack-styling.md
      - Widget Blueprints:     button-pack/button-pack-widget-blueprints.md
      - Creating new buttons:  button-pack/button-pack-creating-new-buttons.md
      - Changelog:             button-pack/changelog.md
  - Misc: 
      - Design Pillars:        design-pillars.md
      - About:                 about.md

extra: 
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/BreeDurbin