site_name: Aphrilâ€™s Widget Library
site_description: Modular Common UI based widgets for Unreal Engine
site_author: Silverkeep Studios
site_url: https://breedurbin.github.io/Aphrils-Widget-Library/

repo_name: BreeDurbin/Aphrils-Widget-Library
repo_url: https://github.com/BreeDurbin/Aphrils-Widget-Library

theme:
  name: material
  features:
    - navigation.sections
    - navigation.expand
    - navigation.top
    - content.code.copy
  palette:
    scheme: slate

markdown_extensions:
  - admonition
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.details
  - pymdownx.inlinehilite
  - attr_list

nav:
  - Overview:                         index.md
  - Requirements:                     requirements.md
  - Button-Pack:
      - Installation:                 button-pack/button-pack-installation.md
      - Changelog:                    button-pack/changelog.md
  - General Guides: 
      - Workflow:                     general-guides/workflow.md
      - Widget Styling:               general-guides/widget-styling.md
      - Widget Blueprints:            general-guides/widget-blueprints.md
      - Material Parameters:          general-guides/material-parameters.md
      - Creating new base shapes:     general-guides/creating-new-shape-textures.md
      - Channel Packing:              general-guides/channel-packing.md
  - Misc: 
      - Design Pillars:               misc/design-pillars.md
      - About:                        misc/about.md

extra: 
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/BreeDurbin