site_name: Silverkeep Studios
site_description: Modular Common UI based widgets for Unreal Engine
site_author: Aphril
site_url: https://breedurbin.github.io/Aphrils-Widget-Library/

repo_name: BreeDurbin/Aphrils-Widget-Library
repo_url: https://github.com/BreeDurbin/Aphrils-Widget-Library

theme:
  name: material
  logo:    assets/Awl_Logo.png
  favicon: assets/Awl_favicon.png
  features:
    - navigation.sections
    - navigation.expand
    - navigation.top
    - navigation.tabs
    - navigation.footer
    - content.code.copy
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
    
markdown_extensions:
  - admonition
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.details
  - pymdownx.inlinehilite
  - attr_list

nav:
  - Overview:                         index.md
  - Button-Pack:
      - Requirements:                 requirements.md
      - Installation:                 button-pack/button-pack-installation.md
      - Widget Blueprint Parameters:  button-pack/widget-blueprint-parameters.md
      - Material Parameters:          button-pack/material-parameters.md
      - Changelog:                    button-pack/changelog.md
  - General Guides: 
      - Workflow:                     general-guides/workflow.md
      - Creating New Themes:          general-guides/creating-new-themes.md
      - Channel Packing:              general-guides/channel-packing.md
  - Misc: 
      - Design Pillars:               misc/design-pillars.md
      - About:                        misc/about.md

extra: 
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/BreeDurbin
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/SKS_Aphril
